# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 377eb967c0c47f2bceeaac0816914ae2f06304932fa4f3a62c0b64f45079d67c1b675b2b2cdd9168c8e61114f7611e32b803b2edf3e8230074b89d251bd9cf6e

test:
  secret_key_base: 0c9068e46e115bef14dc8f6fdc77b8ef086148733fa0dfa2ca4a50b105ecb4311129946668e5c56774bc13da2c9b473ce2b6fa52beced5eb2823f67158e4edc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
